// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9m0quzTr5tJDDY96ROfGiNdVFN9Kf9U',
    appId: '1:862480934936:web:315959c4414d7130e6bb6d',
    messagingSenderId: '862480934936',
    projectId: 'instagram-e151a',
    authDomain: 'instagram-e151a.firebaseapp.com',
    storageBucket: 'instagram-e151a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacJX2I8IUmDLpD8oUohw_dZOZEI2aXjc',
    appId: '1:862480934936:ios:7da53508541b1017e6bb6d',
    messagingSenderId: '862480934936',
    projectId: 'instagram-e151a',
    storageBucket: 'instagram-e151a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacJX2I8IUmDLpD8oUohw_dZOZEI2aXjc',
    appId: '1:862480934936:ios:7da53508541b1017e6bb6d',
    messagingSenderId: '862480934936',
    projectId: 'instagram-e151a',
    storageBucket: 'instagram-e151a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG9m0quzTr5tJDDY96ROfGiNdVFN9Kf9U',
    appId: '1:862480934936:web:53d961cc912e361fe6bb6d',
    messagingSenderId: '862480934936',
    projectId: 'instagram-e151a',
    authDomain: 'instagram-e151a.firebaseapp.com',
    storageBucket: 'instagram-e151a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlFOwaz5ujCmSs2fJbNB3t6bGdj0R3Yxc',
    appId: '1:862480934936:android:3c3a098f2eff10ffe6bb6d',
    messagingSenderId: '862480934936',
    projectId: 'instagram-e151a',
    storageBucket: 'instagram-e151a.firebasestorage.app',
  );

}